manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: urob
      url-base: https://github.com/urob
    - name: PikakueNNZ
      url-base: https://github.com/PikakueNNZ
  projects:
    - name: zmk
      remote: PikakueNNZ
      revision: pr-testing/mouse_ps2_v2
      import: app/west.yml
  self:
    path: config
